# This is a basic workflow to help you get started with Actions

name: Windows build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  compile:
    runs-on: windows-latest
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: little-core-labs/get-git-tag@v3.0.1
        id: tagName
      -
        name: Checkout
        uses: actions/checkout@v2
        with: 
          submodules : true
      -
       # I wish I could use Chocolatey or something else but it's a pain in the but
        name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
      -
        name: Install SPackager
        uses: Skarsnik/sqpackager-action@main
      -
        name: build
        run: SQPackager --build windows
      -
        name: Upload 7zip
        uses: actions/upload-artifact@v2
        with:
          name: ButtonMash.7z
          path: "${{steps.build.outputs.sqpackager_win32_x64_standalone_7zip}}"
      -
        name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
                 "${{steps.build.outputs.sqpackager_win32_x64_standalone_7zip}}"
                 "${{steps.build.outputs.sqpackager_win32_x64_innosetup}}"
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
